<?php
      // include a phpchecker.php -ba
      // gyakran hsznált Joomla osztályok és ezek gyakran használt metodusai
      $w = $this->nameSpace->addFunHelp('void function jimport($name)');
      $w = $this->nameSpace->addFunHelp('void function jexit($msg)');
      $w = $this->nameSpace->addClass('JFactory','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('JDatabase function getDBO()');
           $w->addFunHelp('JRegistry function getConfig()');               
           $w->addFunHelp('JDocument function getDocument()');
           $w->addFunHelp('Jappl function getApplication()');
           $w->addFunHelp('JEditor function getEditor()');
           $w->addFunHelp('JLanguage function getLanguage()');
           $w->addFunHelp('JMail function getMailer()');
           $w->addFunHelp('JSession function getSession()');
           $w->addFunHelp('JUser function getUser()');
           $w->addFunHelp('JURI function getURI()');
           $w->addFunHelp('str function getDate()');
      $w = $this->nameSpace->addClass('JDatabase','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('void function setQuery()');
           $w->addFunHelp('str function getQuery()');
           $w->addFunHelp('object function getObject()');
           $w->addFunHelp('array_of_object function getObjectList()');
           $w->addFunHelp('bool function query()');
           $w->addFunHelp('int function getErrorNum()');
           $w->addFunHelp('str function getErrorMsg()');
           $w->addFunHelp('void function stderr()');
      $w = $this->nameSpace->addClass('JDocument','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('void function addScript($url)');
           $w->addFunHelp('void function addStyleSheet($url)');      
           $w->addFunHelp('string function getLanguage()');
           $w->addFunHelp('void function setBase($base)');
           $w->addFunHelp('void function setDescription($description)');
           $w->addFunHelp('void function setMetaData($name,$content)');
           $w->addFunHelp('void function setTilte($str)');
      $w = $this->nameSpace->addClass('JEditor','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('string function display($name,$html,$w,$h,$col,$row)');
      $w = $this->nameSpace->addClass('JMail','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('void function addAttachment($attachment)');
           $w->addFunHelp('void functiob addBCC($bcc,$name)');
           $w->addFunHelp('void function addCC($cc,$name)');
           $w->addFunHelp('void function addRecipient($recipient,$name)');
           $w->addFunHelp('void function addReplyTo($replyto, $name)');
           $w->addFunHelp('bool|JEror function Send()');
           $w->addFunHelp('void function setBody($content)');
           $w->addFunHelp('void function setSender($from)');
           $w->addFunHelp('void function setSubject($subject)');
           $w->addScalar('charset');      
      $w = $this->nameSpace->addClass('JError','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('void function raiseError($code,$msg)');
           $w->addFunHelp('void function raiseNotice($code,$msg)');
           $w->addFunHelp('void function raiseWarning($code,$msg)');
      $w = $this->nameSpace->addClass('JConfig','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('sitename');
           $w->addFunHelp('editor');
           $w->addFunHelp('list_limit');
           $w->addFunHelp('dbtype');
           $w->addFunHelp('mailer');
           $w->addFunHelp('mailfrom');
           $w->addFunHelp('fromname');
           $w->addFunHelp('MetaTitle');
           $w->addFunHelp('sef');
           $w->addFunHelp('sef_rewrite');
           $w->addFunHelp('sef_suffix');
           $w->addFunHelp('imageBase');
      $w = $this->nameSpace->addClass('JModel','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('array function getItems()');
           $w->addFunHelp('recordObject function getItem($pk)');
           $w->addFunHelp('bool function store($recordObject)');
           $w->addFunHelp('bool finction deletet($pk)');
           $w->addFunHelp('bool function check($recordObject)');
           $w->addFunHelp('bool function canDelete($recordObject)');
           $w->addFunHelp('JDatabase function getDBO()');
           $w->addFunHelp('void function setError($msg)');
           $w->addFunHelp('strd function getErrorMsg()');
      $w = $this->nameSpace->addClass('JModelItem','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('array function getItems()');
           $w->addFunHelp('recordObject function getItem($pk)');
           $w->addFunHelp('bool function store($recordObject)');
           $w->addFunHelp('bool finction deletet($pk)');
           $w->addFunHelp('bool function check($recordObject)');
           $w->addFunHelp('bool function canDelete($recordObject)');
           $w->addFunHelp('JDatabase function getDBO()');
           $w->addFunHelp('void function setError($msg)');
      $w = $this->nameSpace->addClass('JView','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('void function display()');
           $w->addFunHelp('JModel function getModel($modelName)');
           $w->addFunHelp('void function setLayout($name)');
           $w->addFunHelp('str function getLayout($name)');
           $w->addFunHelp('void function set($name,$value)');
           $w->addFunHelp('mixed function get($name)');
      $w = $this->nameSpace->addClass('JViewLegacy','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('void function display()');
           $w->addFunHelp('JModel function getModel($modelName)');
           $w->addFunHelp('void function setLayout($name)');
           $w->addFunHelp('str function getLayout($name)');
           $w->addFunHelp('void function set($name,$value)');
           $w->addFunHelp('mixed function get($name)');
      $w = $this->nameSpace->addClass('JController','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('void function execute($task)');
           $w->addFunHelp('void function display()');
           $w->addFunHelp('void function redirect()');
           $w->addFunHelp('void function setRedirect($url)');
           $w->addFunHelp('JModel function getModel($name)');
           $w->addFunHelp('strComName function getName()');
           $w->addFunHelp('JView function getView($name,$type');
           $w->addFunHelp('str function getMessage()');
           $w->addFunHelp('void function setMessage($str)');
           $w->addFunHelp('void function registerTask($task,$method)');
           $w->addFunHelp('void function registerDefaultTask($method)');
      $w = $this->nameSpace->addClass('JControllerLegacy','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('void function execute($task)');
           $w->addFunHelp('void function display()');
           $w->addFunHelp('void function redirect()');
           $w->addFunHelp('void function setRedirect($url)');
           $w->addFunHelp('JModel function getModel($name)');
           $w->addFunHelp('strComName function getName()');
           $w->addFunHelp('JView function getView($name,$type');
           $w->addFunHelp('str function getMessage()');
           $w->addFunHelp('void function setMessage($str)');
           $w->addFunHelp('void function registerTask($task,$method)');
           $w->addFunHelp('void function registerDefaultTask($method)');
      $w = $this->nameSpace->addClass('JHelper','');
           $w->addFunHelp('void function __construct()');
      $w = $this->nameSpace->addClass('JProfiler','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('JProfiler function getInstance($app)');
      $w = $this->nameSpace->addClass('JTable','');
           $w->addFunHelp('JTable function__construct($tableName,$keyname,&$db)');
           $w->addFunHelp('array function getFields()');
           $w->addFunHelp('str function getTablename()');
           $w->addFunHelp('str function getKeyname()');
           $w->addFunHelp('JDatabase function getDBO()');
           $w->addFunHelp('bool function bind($source)');
           $w->addFunHelp('bool function load($key)');
           $w->addFunHelp('bool function store()');
           $w->addFunHelp('bool function save($src)');
           $w->addFunHelp('bool function delete($pk)');
           $w->addFunHelp('JTable function getInstance($name,$prefix)');
           $w->addFunHelp('void function addIncludePath($path)');
      $w = $this->nameSpace->addClass('JForm','');
           $w->addFunHelp('JForm function __construct()');
           $w->addFunHelp('JForm function getInstance($formName,$XMLfilename)');
           $w->addFunHelp('bool function bind($source)');
           $w->addFunHelp('bool function validate()');
           $w->addFunHelp('JFormField_array function getFields()');
           $w->addFunHelp('JFormField function getField($name)');
           $w->addFunHelp('str function getLabel($name)');
           $w->addFunHelp('str function getTitle($name)');
           $w->addFunHelp('str function getInput($name)');
           $w->addFunHelp('str function getValue($name)');
           $w->addFunHelp('void function setValue($name)');
      $w = $this->nameSpace->addClass('JFormField','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('str function getLabel()'); 
           $w->addFunHelp('str function getTitle()'); 
           $w->addFunHelp('str function getInput()'); 
           $w->addFunHelp('str function getValue()'); 
      $w = $this->nameSpace->addClass('JRequest','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('mixed function get($name,$hash,$mask)'); 
           $w->addFunHelp('str function getVar($name,$default)'); 
           $w->addFunHelp('void function setVar($name,$value)');
           $w->addFunHelp('void function checkToken()');
      $w = $this->nameSpace->addClass('JURI','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('str function base()'); 
           $w->addFunHelp('str function root()'); 
           $w->addFunHelp('str function current()'); 
      $w = $this->nameSpace->addClass('JText','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('str function _($name)'); 
      $w = $this->nameSpace->addClass('JArrayHelper','');
           $w->addFunHelp('void function __construct()');
           $w->addFunHelp('obj function toObject($array,$type)'); 
      $w = $this->nameSpace->addClass('JHtml','');
           $w->addFunHelp('void function _($str)');
      $w = $this->nameSpace->addClass('JPagination','');
           $w->addFunHelp('obj function __construct($total,$limitstart,$limit)');
           $w->addFunHelp('str function getListFooter()');
      
      // Joomla konstansok
      $w = $this->nameSpace->addConstant('JPATH_BASE');
      $w = $this->nameSpace->addConstant('JPATH_ROOT');
      $w = $this->nameSpace->addConstant('JPATH_COMPONENT');
      $w = $this->nameSpace->addConstant('JPATH_TEMPLATE');
      $w = $this->nameSpace->addConstant('JPATH_CONFIGURATION');
      $w = $this->nameSpace->addConstant('JPATH_INSTALLATION');
      $w = $this->nameSpace->addConstant('JPATH_LIBRARIES');
      $w = $this->nameSpace->addConstant('JPATH_SITE');
      $w = $this->nameSpace->addConstant('JPATH_ADMINISTRATOR');
      $w = $this->nameSpace->addConstant('DS');
      $w = $this->nameSpace->addConstant('JDEBUG');
      $w = $this->nameSpace->addConstant('JREQUEST_ALLOWHTML');
?>